### ISSUE TITLE
Can cookiecutter also add a README with templated text and a contributing.md?

### ISSUE THREAD

**Issue by annegentle** [kecorbin/cookiecutter-devnet-learning-lab#2]
I'd love to have all the Learning Lab repos use the same README, and there should only be a few places to fill in:

Title
First sentence saying what the labs do generally.
Answer a couple of questions in the `## About these labs`` section.

Then also next to the README we have a contributing.md file that doesn't need any templated text. Is it possible to make the folder and these two additional files? If so, this is a gold medal!

**Comment by annegentle** [comment]
Oh yes, here are the templated files:

README file https://github.com/CiscoDevNet/devnet-writing-guidelines/blob/master/labs/README.md
contributing.md file https://github.com/CiscoDevNet/devnet-writing-guidelines/blob/master/labs/contributing.md

**Comment by kecorbin** [comment]
@annegentle i think this is addressed in the seperation of learning-lab-module vs learning lab.  

https://github.com/kecorbin/cookiecutter-devnet-learning-module

**Comment by annegentle** [comment]
Yep! Agreed, closing.
